Dockerfile: Specify tags of images
Java versions needs to match. Otherwise, linkage errors arise:

```
Error: LinkageError occurred while loading main class org.example.Main
	java.lang.UnsupportedClassVersionError: org/example/Main has been
	compiled by a more recent version of the Java Runtime (class file
	version 65.0), this version of the Java Runtime only recognizes class
	file versions up to 62.0
````

Use amazoncorretto instead of openjdk. openjdk is deprecated.